# å›¾æ ‡
favicon: /img/favicon.png

# æ ‡é¢˜
banner:
  enable: true
  title: ç´…è‘‰ã®æ£®
  border: false
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# é¢œè‰²
colors:
  primary: "#0078E7"
  bg: "#FFC0CB"
  selection_bg: "#FF1493" # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

# å…¬å‘Š
notice:
  enable: true
  content: ç”±äº Hexo å¯¹æ•°å­¦å…¬å¼çš„æ”¯æŒé—®é¢˜, åˆ é™¤äº†ç¬”è®°å†…å®¹

# äº®æš—æ¨¡å¼
# å¯é€‰ light | dark | auto | time
mode: auto

# æŒ‡é’ˆ
cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

# å¤´åƒ
avatar:
  enable: true
  url: /img/avatar.png
  rounded: true
  opacity: 1
  status:
    enable: true
    emoji: ğŸ“–
    message: æ‹çˆ±ä¸å­¦ä¹ 

# æ‰“èµ
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: /img/alipay.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    #- name: QQ æ”¯ä»˜
      #path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/qqpay-qrcode.png
      #color: "#12B7F5"
      #icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: /img/wechatpay.png
      color: "#2DC100"
      icon: icon-wechat-pay-line

# èµ·å§‹å¹´ä»½
footer:
  since: 2022

# ä»£ç å¤åˆ¶æŒ‰é’®
codeblock:
  copy_btn: true

# ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true

# è¯„è®ºç³»ç»Ÿ
comment:
  candidates:
    - waline
    # - giscus
  tips:
    - è¯·æ–‡æ˜è¯„è®ºå“¦~
waline:
  enable: true
  serverURL: https://waline-server-neon.vercel.app/
  visitor: false
  comment: true

# èƒŒæ™¯
bg_image:
  enable: true
  url: /img/bg_light1.jpg
  dark: /img/bg_dark1.jpg
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

wordcloud:
  enable: true
  height: 350

# ä¾§è¾¹æ 
pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: èµ„æº
    url: /resources/
    icon: icon-cloud-line
    color: green
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink

# ç•™è¨€æ¿
menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: icon-clipboard-line

# è€å©†
girls:
  enable: true

# ç™¾åº¦
baidu_push: true

# ç¤¾äº¤
social:
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: GitHub
    link: https://github.com/Jk-Cheung
    icon: icon-github-line
    color: "#6e5494"
  - name: E-Mail
    link: mailto:jk.momiji1230@gmail.com
    icon: icon-mail-line
    color: "#8E71C1"

# å…¬å¼
katex:
  copy_tex: true
  global: false
mathjax:
  enable: true
  per_page: false
  
# åœç®—å­
busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: true
  page_pv_icon: icon-eye-line
